/**
 * Generator-level gates (design §8.4 gate 2) and the writer's file discipline.
 *
 * These are the refusals that stop a broken profile from ever being written:
 *   - Channel B already active  -> refuse to also write the Channel A managed block;
 *   - a duplicate `serverName`  -> refuse and point at `--migrate`;
 *   - a half-marked block       -> refuse instead of guessing.
 *
 * Plus the two properties the old PowerShell generator owned: a timestamped backup before
 * every write, and LF output without a BOM.
 *
 * Nothing here touches a real profile: every write goes to a temp directory.
 *
 * @module dsh-aura/tests/sync-cli.test
 */

import assert from 'node:assert/strict'
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { after, describe, test } from 'node:test'

import { duplicateServerNames } from '../lib/mcp/managed-block.js'
import { renderBundlePatch, renderManagedBlock } from '../lib/mcp/rows.js'
import { defaultPatchPath, planSync, stamp, writePatchFile } from '../scripts/Sync-AuraMcp.mjs'

const tempDirs = []
after(() => {
  for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true })
})

/**
 * Make a throwaway directory.
 * @returns {string} the directory path.
 */
function tempDir() {
  const dir = mkdtempSync(join(tmpdir(), 'dsh-aura-sync-'))
  tempDirs.push(dir)
  return dir
}

const BUNDLE_PATCH = renderBundlePatch()

/** A profile patch in the pre-migration state. */
const PROFILE_PATCH = ['# profile patch', '- insert:', renderManagedBlock().trimEnd(), ''].join('\n')

/** A profile patch containing a legacy hand-written duplicate of the inspector row. */
const WITH_LEGACY_DUPLICATE = [
  '- insert:',
  '    - id: mcp-aura-unreal-inspector',
  "      name: '@deepseek-ai/dsh-mcp-client'",
  '      config:',
  '        serverName: unreal_inspector',
  '        transport: stdio',
  '        command: legacy-python.exe',
  '',
  renderManagedBlock().trimEnd(),
  '',
].join('\n')

describe('planSync: Channel B mutual exclusion', () => {
  test('refuses to write the Channel A block while Channel B is active', () => {
    const plan = planSync({ text: '# empty\n', bundlePatch: BUNDLE_PATCH, inBundleList: true })
    assert.equal(plan.ok, false)
    assert.match(plan.reason, /Channel B is active/)
    assert.match(plan.reason, /duplicate loader entry id/)
  })

  test('writes normally when Channel B is not in the bundle list', () => {
    const plan = planSync({ text: '# empty\n', bundlePatch: BUNDLE_PATCH, inBundleList: false })
    assert.equal(plan.ok, true)
    assert.equal(plan.action, 'inserted')
  })

  test('reports unchanged for the block that is already in sync', () => {
    const plan = planSync({ text: PROFILE_PATCH })
    assert.equal(plan.ok, true)
    assert.equal(plan.action, 'unchanged')
    assert.equal(plan.text, PROFILE_PATCH)
  })
})

describe('planSync: duplicate serverName refusal', () => {
  test('a legacy duplicate is refused with a pointer at --migrate', () => {
    const plan = planSync({ text: WITH_LEGACY_DUPLICATE })
    assert.equal(plan.ok, false)
    assert.match(plan.reason, /unreal_inspector would appear more than once/)
    assert.match(plan.reason, /--migrate/)
  })

  test('--migrate clears the legacy row and then writes cleanly', () => {
    const plan = planSync({ text: WITH_LEGACY_DUPLICATE, migrate: true })
    assert.equal(plan.ok, true)
    assert.deepEqual(plan.removed, ['mcp-aura-unreal-inspector'])
    assert.deepEqual(duplicateServerNames(plan.text), [])
    assert.equal(plan.text.includes('legacy-python.exe'), false)
    assert.equal(plan.text.includes('mcp-aura-unreal-editor'), true, 'the managed block must survive the migration')
  })
})

describe('planSync: removal and half markers', () => {
  test('--remove deletes the block and leaves the rest of the file', () => {
    const plan = planSync({ text: PROFILE_PATCH, remove: true })
    assert.equal(plan.ok, true)
    assert.equal(plan.action, 'removed')
    assert.equal(plan.text.includes('aura-mcp managed'), false)
    assert.ok(plan.text.startsWith('# profile patch'))
  })

  test('--remove on a file with no block is a reported no-op', () => {
    const plan = planSync({ text: '# nothing here\n', remove: true })
    assert.equal(plan.ok, true)
    assert.equal(plan.action, 'already-absent')
  })

  test('a half-marked file is refused, not guessed', () => {
    const half = '# profile patch\n# >>> aura-mcp managed (generated by Sync-AuraMcp.ps1 - do not edit by hand) >>>\n'
    const plan = planSync({ text: half })
    assert.equal(plan.ok, false)
    assert.match(plan.reason, /markers are incomplete/)
  })
})

describe('writePatchFile', () => {
  test('backs the previous file up before writing', () => {
    const dir = tempDir()
    const file = join(dir, 'cordis.patch.yml')
    writePatchFile(file, '# v1\n')
    const { backup } = writePatchFile(file, '# v2\n', { now: new Date(2020, 0, 2, 3, 4, 5) })
    assert.equal(readFileSync(file, 'utf8'), '# v2\n')
    assert.equal(backup, `${file}.bak-20200102-030405`)
    assert.equal(readFileSync(backup, 'utf8'), '# v1\n')
  })

  test('writes LF without a BOM, and normalizes CRLF/BOM input', () => {
    const dir = tempDir()
    const file = join(dir, 'cordis.patch.yml')
    writePatchFile(file, '\uFEFF# a\r\n# b\r\n')
    const text = readFileSync(file, 'utf8')
    assert.equal(text, '# a\n# b\n')
    assert.equal(text.charCodeAt(0), '#'.charCodeAt(0), 'the BOM must not survive')
  })

  test('the first write to a fresh path creates no backup', () => {
    const dir = tempDir()
    const file = join(dir, 'fresh.yml')
    const { backup } = writePatchFile(file, '[]\n')
    assert.equal(backup, null)
    assert.deepEqual(readdirSync(dir), ['fresh.yml'])
  })
})

describe('defaults', () => {
  test('the default target is the web profile patch layer', () => {
    const path = defaultPatchPath('web')
    assert.ok(/profiles[\\/]web[\\/]cordis\.patch\.yml$/.test(path), `unexpected default path: ${path}`)
  })

  test('the backup stamp is sortable', () => {
    assert.equal(stamp(new Date(2026, 8, 19, 8, 52, 6)), '20260919-085206')
  })

  test('the emitted bundle patch exists on disk and matches the renderer', () => {
    const file = new URL('../cordis.patch.yml', import.meta.url)
    assert.equal(existsSync(file), true)
    assert.equal(readFileSync(file, 'utf8'), BUNDLE_PATCH)
  })
})
