/**
 * Single source of truth for the three Aura MCP loader rows.
 *
 * Everything the MCP wiring needs is rendered from here:
 *   - `renderBundlePatch()`  -> this package's own `cordis.patch.yml`. This is the SHIPPED
 *                               shape: the bundle layer, installed by `plugin_manager`.
 *   - `renderManagedBlockBody()` -> the `# >>> aura-mcp managed >>>` block for the patch-layer
 *                               shape, which lives in `~/.dsh/profiles/web/cordis.patch.yml`
 *                               and hot-reloads. It is the ALTERNATIVE shape, not the default.
 *   - `renderHeadlessOverlay()` -> a standalone `- insert:` overlay for
 *                               `dsh --profile headless --patch <file>`.
 *
 * The two shapes must never both provide the same row id: the loader's
 * duplicate check (`cordis-plugin-loader/lib/index.js` -> `TypeError: duplicate loader
 * entry id`) makes the whole profile fail to boot. `lib/mcp/channels.js` is the guard.
 *
 * ZERO imports on purpose: this module is consumed by the package CLI and by tests, and
 * it must never drag in a dependency that the profile's module fallback may not have.
 *
 * The `!!js` expression shape is byte-for-byte the one that has been running in
 * `profiles/web/cordis.patch.yml` since the Aura wiring was first generated; two real
 * bugs are pinned by tests and must not come back:
 *   1. `pathIsLiteral` — the candidate paths are single-quoted JS strings containing
 *      `\\` escapes. Emitting them with a single backslash turns `\next` into a newline
 *      and silently destroys the first candidate path.
 *   2. `bomTolerated` — a Notepad-saved JSON file starts with U+FEFF; `JSON.parse`
 *      throws on it and the row silently degrades to the fallback literal, so the BOM
 *      is stripped before parsing.
 *
 * @module dsh-aura/lib/mcp/rows
 */

/** Row id of this plugin's own loader row. */
export const AURA_ROW_ID = 'dsh-aura'

/** Bare package name used by this plugin's own loader row. */
export const AURA_PACKAGE_NAME = 'dsh-aura'

/** The upstream implementation re-exported by each named row entry. */
export const MCP_CLIENT = '@deepseek-ai/dsh-mcp-client'

/** Separate package subpaths let DSH resolve row-specific titles and descriptions. */
export const MCP_ENTRY_NAMES = {
  unreal_inspector: 'dsh-aura/mcp/unreal-inspector',
  unreal_editor: 'dsh-aura/mcp/unreal-editor',
  unreal_mcp: 'dsh-aura/mcp/unreal-engine',
}

/** Managed-block markers (Channel A). Kept verbatim: the old generator owned these strings. */
export const MANAGED_BEGIN = '# >>> aura-mcp managed (generated by Sync-AuraMcp.ps1 - do not edit by hand) >>>'
export const MANAGED_END = '# <<< aura-mcp managed <<<'

/** Default per-call budgets (ms). A name containing "editor" gets the longer budget. */
export const DEFAULT_TOOL_CALL_TIMEOUT_MS = 300000
export const EDITOR_TOOL_CALL_TIMEOUT_MS = 900000

/** The Aura MCP servers, in wiring order. */
export const SERVER_NAMES = ['unreal_inspector', 'unreal_editor', 'unreal_mcp']

/**
 * Safe fallbacks baked in at generation time. The two stdio rows use a closed loopback
 * endpoint if neither a pinned Aura installation nor the default local installation
 * can be verified. No author's machine path is shipped.
 */
export const FALLBACKS = {
  unreal_inspector: {
    serverName: 'unreal_inspector',
    transport: 'streamable-http',
    url: 'http://127.0.0.1:1/mcp',
    toolCallTimeoutMs: DEFAULT_TOOL_CALL_TIMEOUT_MS,
    failOnStartupError: false,
  },
  unreal_editor: {
    serverName: 'unreal_editor',
    transport: 'streamable-http',
    url: 'http://127.0.0.1:1/mcp',
    toolCallTimeoutMs: EDITOR_TOOL_CALL_TIMEOUT_MS,
    failOnStartupError: false,
  },
  unreal_mcp: {
    serverName: 'unreal_mcp',
    transport: 'streamable-http',
    url: 'http://127.0.0.1:8000/mcp',
    toolCallTimeoutMs: DEFAULT_TOOL_CALL_TIMEOUT_MS,
    failOnStartupError: false,
  },
}

/**
 * The two candidate config files, as JS source fragments evaluated at loader time.
 * `String.raw` is load-bearing: the double backslashes below must reach the loader as
 * `\\` inside a single-quoted JS string literal (see `pathIsLiteral` above).
 */
const CANDIDATE_PATH_EXPRS = [
  String.raw`(env.LOCALAPPDATA || '') + '\\Programs\\aura-client\\next\\.mcp-config.json'`,
  String.raw`(env.USERPROFILE || '') + '\\.dsh\\aura-mcp.json'`,
]

/** Body of the `!!js` expression, with placeholders substituted by {@link renderConfigExpr}. */
const CONFIG_EXPR_TEMPLATE = String.raw`(() => { const FB = __FALLBACK__;
let auraUp = false;
try {
const fs = globalThis.process.getBuiltinModule('node:fs');
const env = globalThis.process.env;
__GUARD__} catch (e) { auraUp = false; }
if (__GUARDED__ && !auraUp) return __DEAF__;
try { const fs = globalThis.process.getBuiltinModule('node:fs');
const env = globalThis.process.env;
const path = globalThis.process.getBuiltinModule('node:path');
const pinnedRoot = env.DSH_AURA_INSTALL_DIR || '';
const defaultRoot = env.LOCALAPPDATA ? path.join(env.LOCALAPPDATA, 'Programs', 'aura-client') : '';
const cands = [ __CANDIDATES__ ];
const lax = env.DSH_AURA_ALLOW_ANY_COMMAND === '1' || env.DSH_AURA_ALLOW_ANY_COMMAND === 'true';
const okStdio = (s) => { try {
if (typeof s.command !== 'string' || !Array.isArray(s.args) || !s.args.every((x) => typeof x === 'string')) return false;
if (lax) return true;
if (!__GUARDED__ || s.args.length !== 1) return false;
const trusted = pinnedRoot || defaultRoot;
if (!path.isAbsolute(trusted) || !path.isAbsolute(s.command) || !path.isAbsolute(s.args[0])) return false;
const canonical = (p) => { const v = fs.realpathSync(p); return globalThis.process.platform === 'win32' ? v.toLowerCase() : v; };
const root = canonical(trusted);
const command = path.join(root, 'PortablePython', 'Windows', 'python.exe');
const script = path.join(root, 'MCP', FB.serverName + '.py');
const equal = (a, b) => a === (globalThis.process.platform === 'win32' ? b.toLowerCase() : b);
return equal(canonical(s.command), command) && equal(canonical(s.args[0]), script) && fs.statSync(s.command).isFile() && fs.statSync(s.args[0]).isFile();
} catch (e) { return false; } };
const okUrl = (u) => { try { const v = new globalThis.URL(String(u)); const h = v.hostname; return (v.protocol === 'http:' || v.protocol === 'https:') && !v.username && !v.password && (h === '127.0.0.1' || h === 'localhost' || h === '[::1]'); } catch (e) { return false; } };
for (const p of cands) { try { if (!fs.existsSync(p)) continue;
const txt = fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, '');
const raw = JSON.parse(txt);
const map = (raw && raw.mcpServers) ? raw.mcpServers : raw;
const s = map ? map['__SERVER__'] : null;
if (!s) continue;
if (s.url) { if (okUrl(s.url)) return __HTTP__; continue; }
if (s.command) { if (okStdio(s)) return __STDIO__; continue; }
} catch (e) { } }
const fallbackRoot = pinnedRoot || defaultRoot;
if (__GUARDED__ && fallbackRoot && path.isAbsolute(fallbackRoot)) { try {
const command = path.join(fallbackRoot, 'PortablePython', 'Windows', 'python.exe');
const script = path.join(fallbackRoot, 'MCP', FB.serverName + '.py');
if (okStdio({ command, args: [script] })) return { serverName: FB.serverName, transport: 'stdio', command, args: [script], toolCallTimeoutMs: FB.toolCallTimeoutMs, failOnStartupError: false };
} catch (e) { } }
} catch (e) { }
return FB;
})()`

/**
 * The Aura-app bridge guard, spliced in as `__GUARD__` for the two STDIO servers only.
 *
 * WHY THIS EXISTS. Aura's `unreal_inspector.py` / `unreal_editor.py` refuse to start
 * without the desktop app's Python bridge and then RETRY ONCE A SECOND, FOREVER. Measured
 * 2026-09-20 in an isolated sandbox profile (`aura-sh`, headless, Aura not installed):
 *
 *   - a two-word prompt took **67.3 s**, and stderr was nothing but
 *     `No Aura bridge port published at …\aura_server_port.txt. … Refusing to guess a port.`
 *   - the two rows sat in `fiberPhase: loading` indefinitely, while the HTTP row
 *     (`mcp-unreal-engine`) settled to `active`.
 *
 * That is what made the whole harness feel unusable after the first install: the servers
 * are spawned by the MCP client, so no DSH-side `failOnStartupError` can stop them.
 *
 * FAIL-CLOSED, AND THAT IS THE WHOLE POINT. The first version returned the baked stdio
 * literal from its outer `catch`. An independent audit pointed out the polarity was
 * backwards: on any exception -- e.g. `getBuiltinModule` missing before Node 22.3 -- the
 * guard vanished and the retry loop came straight back. Now "cannot tell" means DEAF,
 * never STDIO.
 *
 * WHAT COUNTS AS "THE APP IS UP". Not file existence: the same audit measured that a
 * leftover file from a dead app sailed straight through. This expression is evaluated
 * SYNCHRONOUSLY by the loader (`with (ctx) { eval(expr) }`), so an async TCP probe is not
 * available here. What IS available, and what this checks, is that the bridge file exists
 * AND its content parses as a real TCP port. Missing, unreadable, empty, garbage or
 * out-of-range all mean DEAF.
 *
 * RESIDUAL, stated plainly: a file that is present and well-formed while the bridge is
 * actually dead still passes. Only Aura can close that one, by not retrying forever.
 *
 * ESCAPE HATCH. `DSH_AURA_FORCE_STDIO=1` skips the guard (Aura installed somewhere this
 * does not know about); `DSH_AURA_BRIDGE=<path>` relocates the probe.
 */
const BRIDGE_GUARD = String.raw`const forced = env.DSH_AURA_FORCE_STDIO;
if (forced === '1' || forced === 'true') { auraUp = true; } else {
const bridge = env.DSH_AURA_BRIDGE || ((env.LOCALAPPDATA || '') + '\\Programs\\aura-client\\.Aura\\aura_server_port.txt');
const published = fs.readFileSync(bridge, 'utf8').replace(/^\uFEFF/, '').trim();
const port = Number(published);
auraUp = /^[0-9]+$/.test(published) && Number.isInteger(port) && port > 0 && port < 65536;
}
`

/**
 * The comment block that documents the resolution order above each row.
 *
 * The final line names `Sync-AuraMcp.ps1` — do NOT "fix" that to `.mjs`. The line is part
 * of the managed block that is already running in `profiles/web/cordis.patch.yml`, and
 * `tests/mcp-wiring.test.mjs` asserts the whole block is byte-identical to what this
 * renderer produces. The `.ps1` is kept as a one-line wrapper around the Node generator
 * (`scripts/Sync-AuraMcp.ps1`), so the name is still a real entry point.
 */
const RESOLUTION_COMMENT = [
  `# Resolved at load time from Aura's own config, in this order:`,
  String.raw`#   1) %LOCALAPPDATA%\Programs\aura-client\next\.mcp-config.json  (Aura app; rewritten on project/engine switch)`,
  String.raw`#   2) %USERPROFILE%\.dsh\aura-mcp.json  (written by Aura -> Settings -> MCP Configuration -> Add to Editor,`,
  `#      choosing any client and typing that path - the app honours a custom path as-is)`,
  `# Falls back to the literal value baked in at generation time. Regenerate with: Sync-AuraMcp.ps1`,
]

/** Row indentation inside a `- insert:` list, and the scalar block indentation under it. */
const ROW_INDENT = '    '
const KEY_INDENT = '      '
const BLOCK_INDENT = '        '

/**
 * Loader row id for one Aura server.
 *
 * Rule (unchanged from `Sync-AuraMcp.ps1`): `mcp-aura-<serverName with _ replaced by ->`,
 * except `unreal_mcp`, whose id is hard-coded to `mcp-unreal-engine`.
 * @param {string} serverName - one of {@link SERVER_NAMES}.
 * @returns {string} the loader row id.
 */
export function rowIdFor(serverName) {
  if (serverName === 'unreal_mcp') return 'mcp-unreal-engine'
  return `mcp-aura-${String(serverName).replace(/_/g, '-')}`
}

/**
 * Per-call timeout budget for one Aura server.
 * @param {string} serverName - one of {@link SERVER_NAMES}.
 * @returns {number} timeout in milliseconds.
 */
export function timeoutFor(serverName) {
  return String(serverName).includes('editor') ? EDITOR_TOOL_CALL_TIMEOUT_MS : DEFAULT_TOOL_CALL_TIMEOUT_MS
}

/**
 * Render the `!!js` expression source for one Aura server. The returned text is exactly
 * what the loader evaluates with
 * `new Function('ctx','expr','with (ctx) { return eval(expr) }')`.
 * @param {string} serverName - one of {@link SERVER_NAMES}.
 * @param {object} [options] - overrides for tests / regeneration.
 * @param {object} [options.fallback] - literal fallback baked into the expression.
 * @param {number} [options.toolCallTimeoutMs] - timeout budget used by every branch.
 * @returns {string} the expression source (single line per statement).
 */
export function renderConfigExpr(serverName, options = {}) {
  const fallback = options.fallback ?? FALLBACKS[serverName]
  if (fallback === undefined) throw new Error(`unknown Aura MCP server: ${serverName}`)
  const budget = options.toolCallTimeoutMs ?? timeoutFor(serverName)
  const http = `{ serverName: '${serverName}', transport: 'streamable-http', url: String(s.url), toolCallTimeoutMs: ${budget}, failOnStartupError: false }`
  const stdio = `{ serverName: '${serverName}', transport: 'stdio', command: String(s.command), args: (s.args || []).map(String), toolCallTimeoutMs: ${budget}, failOnStartupError: false }`
  // Handed back instead of a stdio config when the Aura bridge is absent: a dead endpoint
  // that costs no child process. See BRIDGE_GUARD.
  const deaf = `{ serverName: '${serverName}', transport: 'streamable-http', url: 'http://127.0.0.1:1/mcp', toolCallTimeoutMs: ${budget}, failOnStartupError: false }`
  const guarded = serverName !== 'unreal_mcp'
  return CONFIG_EXPR_TEMPLATE.replace('__FALLBACK__', () => JSON.stringify(fallback))
    .replace('__GUARD__', () => (guarded ? BRIDGE_GUARD : ''))
    .replaceAll('__GUARDED__', () => (guarded ? 'true' : 'false'))
    .replace('__DEAF__', () => deaf)
    .replace('__CANDIDATES__', () => CANDIDATE_PATH_EXPRS.join(', '))
    .replace('__SERVER__', () => serverName)
    .replace('__HTTP__', () => http)
    .replace('__STDIO__', () => stdio)
}

/**
 * Wrap one expression into a folded (`>-`) YAML block scalar at the given indentation.
 *
 * Every emitted line sits at exactly `indent`, so js-yaml's folded scalar turns the
 * line breaks back into single spaces and the evaluated expression is identical to the
 * one-line form.
 * @param {string} expr - expression source, possibly multi-line.
 * @param {string} indent - the block indentation (8 spaces inside a row).
 * @returns {string} the YAML block, including a trailing newline.
 */
function foldBlock(expr, indent) {
  return `${expr
    .split('\n')
    .map((line) => `${indent}${line}`)
    .join('\n')}\n`
}

/**
 * Render one MCP loader row as YAML text.
 * @param {string} serverName - one of {@link SERVER_NAMES}.
 * @param {object} [options] - rendering options.
 * @param {string} [options.indent] - row indentation (default: inside a `- insert:` list).
 * @param {boolean} [options.comment] - emit the resolution-order comment block.
 * @param {number} [options.toolCallTimeoutMs] - timeout budget override.
 * @returns {string} the row text (no trailing blank line).
 */
export function renderRow(serverName, options = {}) {
  const rowIndent = options.indent ?? ROW_INDENT
  const keyIndent = `${rowIndent}  `
  const blockIndent = `${rowIndent}    `
  const expr = renderConfigExpr(serverName, options)
  const lines = [`${rowIndent}- id: ${rowIdFor(serverName)}`, `${keyIndent}name: '${MCP_ENTRY_NAMES[serverName]}'`]
  if (options.comment !== false) {
    for (const comment of RESOLUTION_COMMENT) lines.push(`${keyIndent}${comment}`)
  }
  lines.push(`${keyIndent}config: !!js >-`)
  return `${lines.join('\n')}\n${foldBlock(expr, blockIndent).trimEnd()}`
}

/**
 * Render the three MCP rows, blank-line separated, at the given indentation.
 * @param {object} [options] - forwarded to {@link renderRow}.
 * @returns {string} the row bodies.
 */
export function renderMcpRows(options = {}) {
  return SERVER_NAMES.map((serverName) => renderRow(serverName, options)).join('\n\n')
}

/**
 * Render the body of the Channel A managed block (the three MCP rows only).
 * @param {object} [options] - forwarded to {@link renderRow}.
 * @returns {string} the block body without the markers.
 */
export function renderManagedBlockBody(options = {}) {
  return `${renderMcpRows(options)}\n`
}

/**
 * Render a complete Channel A managed block, markers included, as inserted into
 * `~/.dsh/profiles/web/cordis.patch.yml`.
 * @param {object} [options] - forwarded to {@link renderRow}.
 * @returns {string} the managed block text.
 */
export function renderManagedBlock(options = {}) {
  return `${MANAGED_BEGIN}\n${renderManagedBlockBody(options)}${MANAGED_END}\n`
}

/**
 * Render a standalone overlay (`- insert:` wrapper) for
 * `dsh --profile headless --patch <file> <prompt>`.
 * @param {object} [options] - forwarded to {@link renderRow}.
 * @returns {string} the overlay patch text.
 */
export function renderHeadlessOverlay(options = {}) {
  return `# Generated by dsh-aura scripts/Sync-AuraMcp.mjs --emit-overlay - do not edit by hand.\n# Lets a one-shot DSH run drive the Unreal editor.\n- insert:\n${renderMcpRows(options)}\n`
}

/**
 * Render this package's own `cordis.patch.yml` (Channel B: the cold-start bundle layer).
 *
 * The header is deliberately loud about the mutual exclusion with Channel A: providing
 * the same row id from two layers is a `TypeError: duplicate loader entry id` that stops
 * the whole profile from booting.
 * @param {object} [options] - forwarded to {@link renderRow}.
 * @returns {string} the patch file text.
 */
export function renderBundlePatch(options = {}) {
  const header = [
    '# dsh-aura bundle patch -- CHANNEL B (cold start) ONLY.',
    '#',
    '# This file is the layer form of the Aura wiring. It is read by the loader only when',
    '# `dsh-aura` is listed in `dsh.profile.bundles` AND this package declares',
    '# `"dsh": { "bundle": { "patch": "./cordis.patch.yml" } }` in its package.json.',
    '#',
    '# This IS the shipped shape (2026-09-20): package.json declares dsh.bundle and the harness',
    '# installs the package itself (plugin_manager -> install_bundle). See README.md "装载".',
    '#',
    '# THE PATCH-LAYER SHAPE IS MUTUALLY EXCLUSIVE WITH THIS ONE. If',
    '# ~/.dsh/profiles/<name>/cordis.patch.yml also provides one of these ids, the loader throws',
    '# `TypeError: duplicate loader entry id: <id>` and the whole profile fails to boot.',
    '# Switch with scripts/Sync-AuraMcp.mjs (see README.md); check with:',
    '#   node scripts/Sync-AuraMcp.mjs --check',
    '#',
    '# The three MCP config expressions are resolved at load time from Aura\'s own config; see the',
    '# comment above each row.',
    `- insert:`,
    `    - id: ${AURA_ROW_ID}`,
    `      name: '${AURA_PACKAGE_NAME}'`,
  ]
  return `${header.join('\n')}\n${renderMcpRows(options)}\n`
}

/**
 * Every loader row id this package can provide. Used by the Channel A/B guard.
 * @returns {string[]} the four ids.
 */
export function ownedRowIds() {
  return [AURA_ROW_ID, ...SERVER_NAMES.map(rowIdFor)]
}
